language: php

php:
  - 5.4
  - 5.5
  - 5.6
  - hhvm

matrix:
  allow_failures:
    - php: hhvm

before_script:
    - composer self-update
    - composer require satooshi/php-coveralls:dev-master --no-update --dev
    - composer install --prefer-dist
    - cd examples/relational && composer install --prefer-dist
    - php config/init.php
    - php -S localhost:8000 &
    - sleep 3
    - cd ../..
    - wget http://codeception.com/codecept.phar

script:
  - mkdir -p build/logs
  - phpunit --coverage-text
  - php codecept.phar run api -c tests/codecept/codeception.yml
  - ./vendor/bin/phpcs src --standard=psr2

after_script:
  - php vendor/bin/coveralls