language: php

php:
  - 5.4
  - 5.5
  - 5.6
  - hhvm

before_script:
    - travis_retry composer self-update
    - travis_retry composer install --no-interaction --prefer-source --dev
    - cd examples/relational && composer install --prefer-dist
    - php config/init.php
    - php -S localhost:8000 &
    - sleep 3
    - cd ../..

script:
  - mkdir -p build/logs
  - phpunit --coverage-text --verbose --coverage-clover=coverage.clover

after_script:
  - wget https://scrutinizer-ci.com/ocular.phar
  - php ocular.phar code-coverage:upload --format=php-clover coverage.clover