language: php

php:
  - 5.4
  - 5.5
  - 5.6
  - hhvm

matrix:
  allow_failures:
    - php: hhvm

before_script:
    - travis_retry composer self-update
    - travis_retry composer require satooshi/php-coveralls:dev-master --no-update --dev
    - travis_retry composer install --no-interaction --prefer-source --dev
    - cd examples/relational && composer install --prefer-dist
    - php config/init.php
    - php -S localhost:8000 &
    - sleep 3
    - cd ../..

script:
  - mkdir -p build/logs
  - phpunit --coverage-text --verbose
